gui_compile:
  image: node:9
  stage: build
  before_script:
    - npm install --progress=false
    - npm install -g webpack webpack-cli --progress=false
  script:
    - cd gui
    - webpack --verbose

#before_script:
#  -

#gui_compile:
#  script:
#    - cd gui
#    - webpack --verbose
