srv_compile:
  script:
    - make -C server
  artifacts:
    paths:
      - server/zappy_server

srv_connect:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/connect.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/connect.output`"

srv_join:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/join.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/join.output`"

srv_unknown:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/unknown.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/unknown.output`"

srv_player_forward:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/forward.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/forward.output`"

srv_player_death:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 1000 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/death.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/death.output`"

srv_player_broadcast:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/join.input > /tmp/zappy_output &
    - nc -C 0 4242 -w 5 < test/server/broadcast.input
    - cat /tmp/zappy_output | grep "`cat test/server/broadcast.output`"

srv_player_connect_nbr:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/connect_nbr.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/connect_nbr.output`"

srv_player_fork:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 1000 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/gui_connect.input > /tmp/zappy_output &
    - nc -C 0 4242 -w 5 < test/server/fork.input
    - cat /tmp/zappy_output | grep "`sed '1q;d' test/server/fork.output`" && cat /tmp/zappy_output | grep "`sed '2q;d' test/server/fork.output`"

srv_player_incantation_fail:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 1000 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/gui_connect.input > /tmp/zappy_output &
    - nc -C 0 4242 -w 5 < test/server/incantation_fail.input
    - cat /tmp/zappy_output | grep "`cat test/server/incantation_fail.output`"

srv_player_inventory:
  dependencies:
    - srv_compile
  script:
    - ./server/zappy_server -f 10 -n test -c 10 -x 20 -y 20 &
    - nc -C 0 4242 -w 5 < test/server/inventory.input > /tmp/zappy_output
    - cat /tmp/zappy_output | grep "`cat test/server/inventory.output`"