before_script:
  - make -C server

srv_compile:
  script:
    - make -C server

srv_connect:
  script:
    - ./server/zappy_server &
    - timeout 1 nc -C 0 4242 > /tmp/zappy_output&
    - '[ ! -s /tmp/zappy_output ]'

gui_compile:
  script:
    - cd gui
    - webpack --verbose
